import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Brain, CheckCircle2, Clock3, RotateCcw } from "lucide-react";
import { getAssessmentHistory, getActiveAssessment, getAssessmentResult, startAssessment, submitAssessment, type AssessmentQuestion, type AssessmentResult } from "../../data/assessment/assessmentService";
import { useAuth } from "../../contexts/AuthContext";

export type AssessmentStage = "high_school" | "college" | "professional";
type Card = { type: string; title: string; description: string; icon: string };
const CARDS: Record<AssessmentStage, Card[]> = {
 high_school:[
  {type:"high_school_foundation",title:"Foundation & Common",description:"Core academic foundation and general awareness.",icon:""},
  {type:"high_school_pcm",title:"Science",description:"Physics, Chemistry and Mathematics oriented assessment.",icon:""},
  {type:"high_school_pcb",title:"Science — Biology",description:"Physics, Chemistry and Biology oriented assessment.",icon:""},
  {type:"high_school_commerce",title:"Commerce",description:"Accounting, economics and business fundamentals.",icon:""},
  {type:"high_school_arts",title:"Arts / Humanities",description:"History, geography, civics, economics and social sciences.",icon:""},
  {type:"high_school_aptitude",title:"Aptitude",description:"Numerical and quantitative problem solving.",icon:""},
  {type:"high_school_reasoning",title:"Logical Reasoning",description:"Patterns, logic and analytical reasoning.",icon:""},
 ],
 college:[
  {type:"college_common",title:"College Common",description:"Academic, career and software-development fundamentals.",icon:""},
  {type:"college_aptitude",title:"Aptitude",description:"Quantitative and analytical aptitude.",icon:""},
  {type:"college_coding",title:"Coding / Programming",description:"Programming and problem-solving fundamentals.",icon:""},
  {type:"college_dsa",title:"DSA",description:"Language-neutral data structures and algorithm problems.",icon:""},
  {type:"college_technical",title:"Core CS / Technical",description:"DBMS, OS, networks, OOP, web and software engineering.",icon:""},
  {type:"college_career",title:"Career Readiness",description:"Resume, interview, portfolio and career preparation.",icon:""},
 ],
 professional:[
  {type:"professional_common",title:"Professional Common",description:"Work habits, communication, collaboration and career growth.",icon:""},
  {type:"professional_technical",title:"Technical",description:"Engineering, systems, cloud, security and web fundamentals.",icon:""},
  {type:"professional_dsa",title:"DSA",description:"Language-neutral interview-style algorithm problems.",icon:""},
  {type:"professional_situational",title:"Workplace Situational",description:"Realistic workplace decisions and professional judgement.",icon:""},
 ]
};

export default function AssessmentHub({stage}:{stage:AssessmentStage}){
 const {user}=useAuth(); const cards=CARDS[stage];
 const [selected,setSelected]=useState<Card|null>(null),[questions,setQuestions]=useState<AssessmentQuestion[]>([]),[attemptId,setAttemptId]=useState<number|null>(null),[answers,setAnswers]=useState<Record<number,string>>({}),[index,setIndex]=useState(0),[seconds,setSeconds]=useState(1800),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null),[result,setResult]=useState<AssessmentResult|null>(null),[latest,setLatest]=useState<Record<string,AssessmentResult>>({});
 const loadLatest=async()=>{try{const allowed=new Set(cards.map(c=>c.type));const h=await getAssessmentHistory(50);const done=h.filter(x=>x.status==="completed"&&allowed.has(x.assessment_type));const vals=await Promise.all(done.map(async x=>[x.assessment_type,await getAssessmentResult(x.id)] as const));const m:Record<string,AssessmentResult>={};for(const [t,r] of vals)if(!m[t])m[t]=r;setLatest(m);}catch{}};
 useEffect(()=>{void loadLatest();},[user?.id]);
 useEffect(()=>{if(!attemptId||result)return;if(seconds<=0){void finish();return;}const id=window.setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>window.clearInterval(id);},[attemptId,result,seconds]);
 const start=async(card:Card)=>{setSelected(card);setError(null);setLoading(true);setResult(null);setAnswers({});setIndex(0);try{let a;let resumed=false;try{a=await startAssessment(card.type);}catch(e){if(!(e instanceof Error)||!e.message.toLowerCase().includes("active assessment"))throw e;a=await getActiveAssessment(card.type);resumed=true;}setAttemptId(a.attempt.id);setQuestions(a.questions);if(resumed){const startedAtMs=Date.parse(a.attempt.started_at);const elapsedSeconds=Number.isFinite(startedAtMs)?Math.floor((Date.now()-startedAtMs)/1000):0;setSeconds(Math.max(1,Math.min(1800,1800-elapsedSeconds)));}else{setSeconds(1800);}}catch(e){setError(e instanceof Error?e.message:"Unable to start assessment.");setAttemptId(null);setQuestions([]);}finally{setLoading(false);}};
 async function finish(){if(!attemptId||!questions.length||loading)return;setLoading(true);setError(null);try{const r=await submitAssessment(attemptId,questions.map(q=>({question_id:q.id,selected_answer:answers[q.id]??""})));setResult(r);setAttemptId(null);await loadLatest();}catch(e){setError(e instanceof Error?e.message:"Unable to submit assessment.");}finally{setLoading(false);}}
 const current=questions[index], mm=String(Math.floor(seconds/60)).padStart(2,"0"), ss=String(seconds%60).padStart(2,"0");
 if(result&&selected)return <div className="space-y-6"><div className="rounded-3xl border border-emerald-200 bg-emerald-50 p-8"><CheckCircle2 className="text-emerald-600" size={42}/><p className="mt-4 text-sm font-semibold uppercase tracking-wider text-emerald-700">Assessment completed</p><h1 className="mt-2 text-3xl font-bold text-slate-900">{selected.title}</h1><p className="mt-4 text-5xl font-black text-slate-900">{result.correct_answers}/{result.total_questions}</p><p className="mt-1 text-slate-600">{Math.round(result.percentage)}% • Grade {result.grade??"—"}</p></div><button onClick={()=>{setSelected(null);setResult(null);}} className="rounded-xl bg-cyan-600 px-6 py-3 font-semibold text-white">Back to Assessments</button></div>;
 if(attemptId&&current&&selected)return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><button onClick={()=>{setAttemptId(null);setQuestions([]);setSelected(null);}} className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600"><ArrowLeft size={17}/> Exit</button><div className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-bold shadow-sm"><Clock3 size={17}/> {mm}:{ss}</div></div><div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div className="flex justify-between text-sm text-slate-500"><span>Question {index+1} of {questions.length}</span><span>{Object.keys(answers).length} answered</span></div><div className="mt-6 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-cyan-600" style={{width:`${((index+1)/questions.length)*100}%`}}/></div><h2 className="mt-8 text-2xl font-bold leading-9 text-slate-900">{current.question_text}</h2><div className="mt-7 grid gap-3">{(["a","b","c","d"] as const).map(letter=>{const text=current[`option_${letter}`];if(!text)return null;const active=answers[current.id]===letter.toUpperCase();return <button key={letter} onClick={()=>setAnswers(a=>({...a,[current.id]:letter.toUpperCase()}))} className={`flex items-start gap-4 rounded-2xl border p-4 text-left ${active?"border-cyan-500 bg-cyan-50":"border-slate-200 hover:border-cyan-300"}`}><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border font-bold">{letter.toUpperCase()}</span><span className="pt-1 font-medium text-slate-800">{text}</span></button>})}</div><div className="mt-8 flex justify-between gap-3"><button disabled={index===0} onClick={()=>setIndex(i=>Math.max(0,i-1))} className="rounded-xl border px-5 py-3 font-semibold disabled:opacity-40">Previous</button>{index===questions.length-1?<button onClick={()=>void finish()} disabled={loading} className="rounded-xl bg-cyan-600 px-6 py-3 font-semibold text-white disabled:opacity-50">{loading?"Submitting…":"Submit Assessment"}</button>:<button onClick={()=>setIndex(i=>Math.min(questions.length-1,i+1))} className="inline-flex items-center gap-2 rounded-xl bg-cyan-600 px-6 py-3 font-semibold text-white">Next <ArrowRight size={17}/></button>}</div></div></div>;
 return <div className="space-y-7"><div className="rounded-3xl bg-gradient-to-r from-cyan-50 via-white to-blue-50 p-7"><p className="font-semibold text-cyan-700">Assessment Center</p><h1 className="mt-2 text-3xl font-black text-slate-900">Choose what you want to assess</h1><p className="mt-2 max-w-2xl text-slate-600">Assessments are independent. Your profile stream does not lock your choices. Every attempt contains 10 questions from the selected bank.</p><div className="mt-5 inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-semibold text-slate-700 shadow-sm"><Brain size={17}/> {Object.keys(latest).length} completed assessment types</div></div>{error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-700">{error}</div>}<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{cards.map(card=><div key={card.type} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm hover:shadow-md"><div className="flex items-start justify-between"><div className="h-1" aria-hidden="true" />{latest[card.type]&&<span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{Math.round(latest[card.type].percentage)}%</span>}</div><h2 className="mt-5 text-xl font-bold text-slate-900">{card.title}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-slate-600">{card.description}</p><button disabled={loading} onClick={()=>void start(card)} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-cyan-600 px-5 py-3 font-semibold text-white disabled:opacity-50">{latest[card.type]?<RotateCcw size={17}/>:<ArrowRight size={17}/>} {latest[card.type]?"Retake Assessment":"Start Assessment"}</button></div>)}</div></div>;
}
