export type ProfessionalProfile = { fullName:string; email:string; company:string; designation:string; experience:string; industry:string; skills:string; phone:string; city:string; state:string; linkedin:string; github:string; portfolio:string; expectedSalary:string; careerGoal:string; targetRole:string };
export type ProfessionalEvidence = { assessmentScores:number[]; interviewScores:number[]; certifications:string[]; learningCompleted:string[]; applications:{company:string;role:string;status:string}[]; resumeText:string };
const profileKey=(id:string)=>`talentsphere_professional_profile_${id}`;
const evidenceKey=(id:string)=>`talentsphere_professional_evidence_${id}`;
export const emptyProfessionalProfile=(name="",email=""):ProfessionalProfile=>({fullName:name,email,company:"",designation:"",experience:"",industry:"",skills:"",phone:"",city:"",state:"",linkedin:"",github:"",portfolio:"",expectedSalary:"",careerGoal:"",targetRole:""});
export function getProfessionalProfile(id:string,name="",email=""){try{return {...emptyProfessionalProfile(name,email),...JSON.parse(localStorage.getItem(profileKey(id))||"{}")}}catch{return emptyProfessionalProfile(name,email)}}
export function saveProfessionalProfile(id:string,v:ProfessionalProfile){localStorage.setItem(profileKey(id),JSON.stringify(v))}
export const emptyEvidence=():ProfessionalEvidence=>({assessmentScores:[],interviewScores:[],certifications:[],learningCompleted:[],applications:[],resumeText:""});
export function getProfessionalEvidence(id:string):ProfessionalEvidence{try{return {...emptyEvidence(),...JSON.parse(localStorage.getItem(evidenceKey(id))||"{}")}}catch{return emptyEvidence()}}
export function saveProfessionalEvidence(id:string,v:ProfessionalEvidence){localStorage.setItem(evidenceKey(id),JSON.stringify(v))}
const avg=(a:number[])=>a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):0;
export function professionalStats(id:string,name="",email=""){const p=getProfessionalProfile(id,name,email),e=getProfessionalEvidence(id); const profileFields=[p.company,p.designation,p.experience,p.industry,p.skills,p.careerGoal,p.targetRole]; const profile=Math.round(profileFields.filter(Boolean).length/profileFields.length*100); const skill=avg(e.assessmentScores); const interview=avg(e.interviewScores); const resume=Math.min(100,(p.skills?20:0)+(p.designation?15:0)+(p.company?15:0)+(p.linkedin?15:0)+(p.portfolio||p.github?15:0)+(e.resumeText.trim().length>120?20:0)); const certification=Math.min(100,e.certifications.length*20); const learning=Math.min(100,e.learningCompleted.length*20); const promotion=Math.round(profile*.2+skill*.3+interview*.2+resume*.2+certification*.1); const career=Math.round((promotion+learning+skill)/3); return {profile,skill,interview,resume,certification,learning,promotion,career,e,p}}
export const roleSkills=(role:string)=>{const r=role.toLowerCase(); if(r.includes('data'))return ['SQL','Python','Data Visualization','Statistics']; if(r.includes('manager')||r.includes('lead'))return ['Leadership','Communication','Stakeholder Management','Planning']; if(r.includes('cloud'))return ['Cloud','Docker','Networking','Security']; return ['Communication','Problem Solving','Industry Knowledge','Leadership']};
