import { useEffect, useState } from "react";
import { Award, BookOpen, Target, TrendingUp } from "lucide-react";
import { useAuth } from "../../contexts/AuthContext";
import { calculateWorkspaceStats, getSubjectProgress, saveSubjectProgress } from "../../services/highSchoolWorkspaceService";
import { getUserAssessmentResults } from "../../data/assessment/assessmentService";
function AcademicProgress(){const {user}=useAuth();const [subjects,setSubjects]=useState<Record<string,number>>({});const [,refresh]=useState(0);
 useEffect(()=>{if(user)setSubjects(getSubjectProgress(user.id))},[user]);if(!user)return null;const stats=calculateWorkspaceStats(user.id);const analyses=getUserAssessmentResults(user.id);const assessmentAverage=analyses.length?Math.round(analyses.reduce((s,a)=>s+a.percentage,0)/analyses.length):0;const overall=Math.round((stats.overall+assessmentAverage)/2);
 const save=(name:string,value:number)=>{const n={...subjects,[name]:Math.max(0,Math.min(100,value))};setSubjects(n);saveSubjectProgress(user.id,n);refresh(x=>x+1)};
 const cards=[["Overall Progress",`${overall}%`,TrendingUp],["Assessments",`${analyses.length} / 5`,BookOpen],["Today's Goals",`${stats.goalPercent}%`,Target],["Completed Assignments",String(stats.completedAssignments),Award]] as const;
 return <div className="mx-auto max-w-5xl space-y-5"><div><h1 className="text-3xl font-bold">Academic Progress</h1><p className="mt-1 text-slate-600">Progress is calculated from your assessments, goals, assignments and subject tracking.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([t,v,I])=><div key={t} className="rounded-2xl border bg-white p-5"><I className="text-cyan-600"/><p className="mt-3 text-sm text-slate-500">{t}</p><strong className="text-2xl">{v}</strong></div>)}</div>
 <section className="rounded-2xl border bg-white p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-xl font-bold">Subject Progress</h2><p className="text-sm text-slate-500">Add subjects and update your completion percentage.</p></div><button className="secondary" onClick={()=>{const name=prompt("Subject name");if(name?.trim())save(name.trim(),0)}}>+ Add Subject</button></div><div className="mt-5 space-y-4">{!Object.keys(subjects).length?<p className="rounded-xl bg-slate-50 p-5 text-slate-500">No subject progress added yet.</p>:Object.entries(subjects).map(([name,value])=><div key={name}><div className="mb-2 flex items-center justify-between"><span className="font-medium">{name}</span><div className="flex items-center gap-2"><input type="number" min="0" max="100" className="w-20 rounded-lg border px-2 py-1" value={value} onChange={e=>save(name,Number(e.target.value))}/><span>%</span><button className="text-red-500" onClick={()=>{const n={...subjects};delete n[name];setSubjects(n);saveSubjectProgress(user.id,n)}}>×</button></div></div><div className="h-2.5 rounded-full bg-slate-200"><div className="h-2.5 rounded-full bg-cyan-600" style={{width:`${value}%`}}/></div></div>)}</div></section></div>}
export default AcademicProgress;