import { useEffect, useState } from "react";
import { BookOpen, CalendarDays, Clock3, MapPin, Pencil, Plus, Trash2, X } from "lucide-react";
import { useAuth } from "../../contexts/AuthContext";
import { getExams, saveExams, type Exam } from "../../services/highSchoolWorkspaceService";
const empty={subject:"",title:"School Examination",date:"",time:"",room:""};
function UpcomingExams(){const {user}=useAuth();const [items,setItems]=useState<Exam[]>([]);const [form,setForm]=useState(empty);const [editing,setEditing]=useState<string|null>(null);const [open,setOpen]=useState(false);
 useEffect(()=>{if(user)setItems(getExams(user.id))},[user]);const persist=(n:Exam[])=>{if(user){setItems(n);saveExams(user.id,n)}};
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(!form.subject||!form.date||!form.time)return;const n=editing?items.map(i=>i.id===editing?{...i,...form}:i):[...items,{id:crypto.randomUUID(),...form}];persist(n);setForm(empty);setEditing(null);setOpen(false)};
 return <div className="mx-auto max-w-5xl space-y-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-bold text-slate-900">Upcoming Exams</h1><p className="mt-1 text-slate-600">Maintain your actual examination schedule.</p></div><button className="primary" onClick={()=>{setForm(empty);setEditing(null);setOpen(true)}}><Plus size={17}/>Add Exam</button></div>
 {open&&<form onSubmit={submit} className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-2"><input className="field" placeholder="Subject" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/><input className="field" placeholder="Exam title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input className="field" type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><input className="field" type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/><input className="field md:col-span-2" placeholder="Room / venue (optional)" value={form.room} onChange={e=>setForm({...form,room:e.target.value})}/><div className="flex gap-2 md:col-span-2"><button className="primary">{editing?"Update":"Save"} Exam</button><button type="button" className="secondary" onClick={()=>setOpen(false)}><X size={17}/>Cancel</button></div></form>}
 {!items.length?<div className="rounded-2xl border border-dashed bg-white p-10 text-center text-slate-500">No exams added yet.</div>:<div className="space-y-3">{items.sort((a,b)=>a.date.localeCompare(b.date)).map(i=><div key={i.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div className="flex gap-3"><div className="iconbox"><BookOpen size={22}/></div><div><h2 className="text-xl font-bold">{i.subject}</h2><p className="text-slate-500">{i.title}</p></div></div><div className="flex flex-wrap items-center gap-3 text-sm"><span className="meta"><CalendarDays size={16}/>{i.date}</span><span className="meta"><Clock3 size={16}/>{i.time}</span>{i.room&&<span className="meta"><MapPin size={16}/>{i.room}</span>}<button className="iconbtn" onClick={()=>{setForm({subject:i.subject,title:i.title,date:i.date,time:i.time,room:i.room});setEditing(i.id);setOpen(true)}}><Pencil size={17}/></button><button className="iconbtn text-red-600" onClick={()=>persist(items.filter(x=>x.id!==i.id))}><Trash2 size={17}/></button></div></div></div>)}</div>}</div>}
export default UpcomingExams;