from ..enums import Difficulty, QuestionType, Topic
from ..schemas import Question


COLLEGE_APTITUDE_QUESTIONS: list[Question] = [

    Question(
        question_code="COLLEGE-APT-001",
        assessment_type="college_aptitude",
        question='A shop offers 20% discount on an item marked ₹1,500. What is the selling price?',
        options=['₹1,100', '₹1,200', '₹1,250', '₹1,300'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.PERCENTAGE,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='20% of ₹1,500 is ₹300, so the selling price is ₹1,200.',
    ),

    Question(
        question_code="COLLEGE-APT-002",
        assessment_type="college_aptitude",
        question='A number is increased from 400 to 460. What is the percentage increase?',
        options=['10%', '12%', '15%', '20%'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.PERCENTAGE,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='The increase is 60; 60/400×100 = 15%.',
    ),

    Question(
        question_code="COLLEGE-APT-003",
        assessment_type="college_aptitude",
        question='The ratio of boys to girls is 3:2. If there are 25 students, how many are girls?',
        options=['8', '10', '12', '15'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.RATIO_PROPORTION,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Girls are 2 of 5 parts, so 25×2/5 = 10.',
    ),

    Question(
        question_code="COLLEGE-APT-004",
        assessment_type="college_aptitude",
        question='If 5 pens cost ₹75, what will 8 pens cost at the same rate?',
        options=['₹100', '₹110', '₹120', '₹125'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.RATIO_PROPORTION,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='One pen costs ₹15; 8 pens cost ₹120.',
    ),

    Question(
        question_code="COLLEGE-APT-005",
        assessment_type="college_aptitude",
        question='The average of 12, 18, 20 and 30 is:',
        options=['18', '20', '22', '24'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.AVERAGE,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='The sum is 80 and 80/4 = 20.',
    ),

    Question(
        question_code="COLLEGE-APT-006",
        assessment_type="college_aptitude",
        question='The average of five numbers is 24. If four of them total 86, the fifth is:',
        options=['30', '32', '34', '36'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.AVERAGE,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Total is 120; 120−86 = 34.',
    ),

    Question(
        question_code="COLLEGE-APT-007",
        assessment_type="college_aptitude",
        question='An article costs ₹800 and is sold for ₹920. What is the profit percentage?',
        options=['10%', '12%', '15%', '20%'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.PROFIT_LOSS,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Profit is ₹120; 120/800×100 = 15%.',
    ),

    Question(
        question_code="COLLEGE-APT-008",
        assessment_type="college_aptitude",
        question='An item bought for ₹1,200 is sold at a loss of 10%. Its selling price is:',
        options=['₹1,020', '₹1,080', '₹1,100', '₹1,120'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.PROFIT_LOSS,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='90% of ₹1,200 is ₹1,080.',
    ),

    Question(
        question_code="COLLEGE-APT-009",
        assessment_type="college_aptitude",
        question='What is the simple interest on ₹5,000 at 8% per annum for 2 years?',
        options=['₹600', '₹700', '₹800', '₹900'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.SIMPLE_INTEREST,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='SI = 5000×8×2/100 = ₹800.',
    ),

    Question(
        question_code="COLLEGE-APT-010",
        assessment_type="college_aptitude",
        question='A sum earns ₹540 simple interest in 3 years at 6%. The principal is:',
        options=['₹2,500', '₹3,000', '₹3,500', '₹4,000'],
        answer="B",
        difficulty=Difficulty.MEDIUM,
        question_type=QuestionType.APTITUDE,
        topic=Topic.SIMPLE_INTEREST,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='P = 540×100/(6×3) = ₹3,000.',
    ),

    Question(
        question_code="COLLEGE-APT-011",
        assessment_type="college_aptitude",
        question='What is the amount on ₹10,000 at 10% compound interest for 2 years, annually compounded?',
        options=['₹11,000', '₹12,000', '₹12,100', '₹12,200'],
        answer="C",
        difficulty=Difficulty.MEDIUM,
        question_type=QuestionType.APTITUDE,
        topic=Topic.COMPOUND_INTEREST,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Amount = 10000×1.1² = ₹12,100.',
    ),

    Question(
        question_code="COLLEGE-APT-012",
        assessment_type="college_aptitude",
        question='A can finish a task in 10 days and B in 15 days. Working together, they finish it in:',
        options=['5 days', '6 days', '7 days', '8 days'],
        answer="B",
        difficulty=Difficulty.MEDIUM,
        question_type=QuestionType.APTITUDE,
        topic=Topic.TIME_WORK,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Combined rate is 1/10+1/15 = 1/6, so 6 days.',
    ),

    Question(
        question_code="COLLEGE-APT-013",
        assessment_type="college_aptitude",
        question='If 6 workers complete a job in 12 days, how many days will 8 workers take at the same rate?',
        options=['8', '9', '10', '12'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.TIME_WORK,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Work is constant: 6×12 = 8×d, so d = 9.',
    ),

    Question(
        question_code="COLLEGE-APT-014",
        assessment_type="college_aptitude",
        question='A car travels 240 km in 4 hours. Its average speed is:',
        options=['50 km/h', '55 km/h', '60 km/h', '65 km/h'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.TIME_DISTANCE,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Speed = 240/4 = 60 km/h.',
    ),

    Question(
        question_code="COLLEGE-APT-015",
        assessment_type="college_aptitude",
        question='A train travels at 72 km/h. How far will it travel in 25 minutes?',
        options=['24 km', '30 km', '36 km', '40 km'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.TIME_DISTANCE,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='25 minutes is 5/12 hour; 72×5/12 = 30 km.',
    ),

    Question(
        question_code="COLLEGE-APT-016",
        assessment_type="college_aptitude",
        question='A fair die is rolled once. Probability of getting an even number is:',
        options=['1/6', '1/3', '1/2', '2/3'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.PROBABILITY,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Three of six outcomes are even, giving 1/2.',
    ),

    Question(
        question_code="COLLEGE-APT-017",
        assessment_type="college_aptitude",
        question='A bag has 3 red and 2 blue balls. Probability of drawing a blue ball is:',
        options=['1/5', '2/5', '1/2', '3/5'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.PROBABILITY,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='There are 2 blue balls out of 5.',
    ),

    Question(
        question_code="COLLEGE-APT-018",
        assessment_type="college_aptitude",
        question='How many ways can 3 different books be arranged on a shelf?',
        options=['3', '6', '9', '12'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.PERMUTATION_COMBINATION,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='The number of arrangements is 3! = 6.',
    ),

    Question(
        question_code="COLLEGE-APT-019",
        assessment_type="college_aptitude",
        question='How many ways can 2 students be selected from 5 students?',
        options=['5', '8', '10', '20'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.PERMUTATION_COMBINATION,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='5C2 = 10.',
    ),

    Question(
        question_code="COLLEGE-APT-020",
        assessment_type="college_aptitude",
        question='What is the remainder when 125 is divided by 8?',
        options=['3', '4', '5', '6'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.NUMBER_SYSTEM,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='8×15 = 120, leaving remainder 5.',
    ),

    Question(
        question_code="COLLEGE-APT-021",
        assessment_type="college_aptitude",
        question='Which of the following is divisible by 9?',
        options=['235', '342', '451', '527'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.NUMBER_SYSTEM,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='The digits of 342 sum to 9.',
    ),

    Question(
        question_code="COLLEGE-APT-022",
        assessment_type="college_aptitude",
        question='Evaluate: 48 ÷ 6 × 3.',
        options=['8', '18', '24', '30'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.SIMPLIFICATION,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Division and multiplication are evaluated left to right: 8×3 = 24.',
    ),

    Question(
        question_code="COLLEGE-APT-023",
        assessment_type="college_aptitude",
        question='Evaluate: 25 + 15 × 2 - 10.',
        options=['40', '45', '50', '55'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.SIMPLIFICATION,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Multiplication first gives 30; 25+30−10 = 45.',
    ),

    Question(
        question_code="COLLEGE-APT-024",
        assessment_type="college_aptitude",
        question='If 3x + 7 = 25, x equals:',
        options=['4', '5', '6', '7'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.ALGEBRA,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='3x = 18, so x = 6.',
    ),

    Question(
        question_code="COLLEGE-APT-025",
        assessment_type="college_aptitude",
        question='If x/4 = 7, then x is:',
        options=['21', '24', '28', '32'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.ALGEBRA,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Multiply both sides by 4: x = 28.',
    ),

    Question(
        question_code="COLLEGE-APT-026",
        assessment_type="college_aptitude",
        question='A student scores 70, 80, 90 and 60 in four tests. What is the average score?',
        options=['70', '75', '80', '85'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.DATA_INTERPRETATION,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Total is 300; 300/4 = 75.',
    ),

    Question(
        question_code="COLLEGE-APT-027",
        assessment_type="college_aptitude",
        question='A store sold 120 units in January and 150 in February. The increase was:',
        options=['20', '25', '30', '35'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.DATA_INTERPRETATION,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='150−120 = 30 units.',
    ),

    Question(
        question_code="COLLEGE-APT-028",
        assessment_type="college_aptitude",
        question='A ₹2,000 item receives successive discounts of 10% and 20%. Final price is:',
        options=['₹1,400', '₹1,440', '₹1,500', '₹1,600'],
        answer="B",
        difficulty=Difficulty.MEDIUM,
        question_type=QuestionType.APTITUDE,
        topic=Topic.MIXED_ADVANCED,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Final price = 2000×0.9×0.8 = ₹1,440.',
    ),

    Question(
        question_code="COLLEGE-APT-029",
        assessment_type="college_aptitude",
        question='If 40% of a number is 72, the number is:',
        options=['160', '170', '180', '190'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.MIXED_ADVANCED,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='72/0.4 = 180.',
    ),

    Question(
        question_code="COLLEGE-APT-030",
        assessment_type="college_aptitude",
        question="A student's marks rise from 60 to 75. Percentage increase is:",
        options=['20%', '25%', '30%', '35%'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.PERCENTAGE,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Increase is 15; 15/60×100 = 25%.',
    ),

    Question(
        question_code="COLLEGE-APT-031",
        assessment_type="college_aptitude",
        question='If x:y = 4:5 and y:z = 10:3, then x:z is:',
        options=['4:3', '8:3', '5:3', '8:5'],
        answer="B",
        difficulty=Difficulty.MEDIUM,
        question_type=QuestionType.APTITUDE,
        topic=Topic.RATIO_PROPORTION,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Make y equal: 4:5 = 8:10, so x:z = 8:3.',
    ),

    Question(
        question_code="COLLEGE-APT-032",
        assessment_type="college_aptitude",
        question='The average age of 4 students is 20. A fifth student aged 25 joins. New average is:',
        options=['20', '21', '22', '23'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.AVERAGE,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Old total is 80; new total is 105; 105/5 = 21.',
    ),

    Question(
        question_code="COLLEGE-APT-033",
        assessment_type="college_aptitude",
        question='An item marked ₹2,500 is sold for ₹2,125. Discount percentage is:',
        options=['10%', '12%', '15%', '20%'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.PROFIT_LOSS,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Discount is ₹375; 375/2500×100 = 15%.',
    ),

    Question(
        question_code="COLLEGE-APT-034",
        assessment_type="college_aptitude",
        question='At what rate will ₹4,000 earn ₹960 simple interest in 4 years?',
        options=['4%', '5%', '6%', '8%'],
        answer="C",
        difficulty=Difficulty.MEDIUM,
        question_type=QuestionType.APTITUDE,
        topic=Topic.SIMPLE_INTEREST,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='R = 960×100/(4000×4) = 6%.',
    ),

    Question(
        question_code="COLLEGE-APT-035",
        assessment_type="college_aptitude",
        question='A pipe fills a tank in 8 hours. What fraction of the tank does it fill in 3 hours?',
        options=['1/8', '3/8', '5/8', '3/5'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.TIME_WORK,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='The rate is 1/8 tank per hour, so 3 hours gives 3/8.',
    ),

    Question(
        question_code="COLLEGE-APT-036",
        assessment_type="college_aptitude",
        question='A person walks at 5 km/h for 36 minutes. Distance covered is:',
        options=['2 km', '2.5 km', '3 km', '3.5 km'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.TIME_DISTANCE,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='36 minutes is 0.6 hour; 5×0.6 = 3 km.',
    ),

    Question(
        question_code="COLLEGE-APT-037",
        assessment_type="college_aptitude",
        question='Two fair coins are tossed. Probability of getting exactly one head is:',
        options=['1/4', '1/2', '3/4', '1'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.PROBABILITY,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='HT and TH are 2 of 4 equally likely outcomes.',
    ),

    Question(
        question_code="COLLEGE-APT-038",
        assessment_type="college_aptitude",
        question='How many 2-digit numbers can be formed using 1,2,3,4 without repetition?',
        options=['8', '10', '12', '16'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.PERMUTATION_COMBINATION,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='4 choices for the first digit and 3 for the second: 12.',
    ),

    Question(
        question_code="COLLEGE-APT-039",
        assessment_type="college_aptitude",
        question='The HCF of 18 and 24 is:',
        options=['3', '6', '9', '12'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.NUMBER_SYSTEM,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='The greatest common factor is 6.',
    ),

    Question(
        question_code="COLLEGE-APT-040",
        assessment_type="college_aptitude",
        question='The LCM of 12 and 15 is:',
        options=['30', '45', '60', '90'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.NUMBER_SYSTEM,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='The least common multiple is 60.',
    ),

    Question(
        question_code="COLLEGE-APT-041",
        assessment_type="college_aptitude",
        question='Evaluate: (18 + 6) ÷ 3 + 4.',
        options=['10', '12', '14', '16'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.SIMPLIFICATION,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='24/3 + 4 = 12.',
    ),

    Question(
        question_code="COLLEGE-APT-042",
        assessment_type="college_aptitude",
        question='If 2x - 5 = 17, x equals:',
        options=['9', '10', '11', '12'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.ALGEBRA,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='2x = 22, so x = 11.',
    ),

    Question(
        question_code="COLLEGE-APT-043",
        assessment_type="college_aptitude",
        question='A candidate gets 45 out of 60 marks. What percentage is this?',
        options=['65%', '70%', '75%', '80%'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.DATA_INTERPRETATION,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='45/60×100 = 75%.',
    ),

    Question(
        question_code="COLLEGE-APT-044",
        assessment_type="college_aptitude",
        question='A number is first increased by 25% and then decreased by 20%. Compared with the original, it is:',
        options=['5% higher', 'Same', '5% lower', '10% lower'],
        answer="B",
        difficulty=Difficulty.MEDIUM,
        question_type=QuestionType.APTITUDE,
        topic=Topic.MIXED_ADVANCED,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='1.25×0.80 = 1, so the final value is unchanged.',
    ),

    Question(
        question_code="COLLEGE-APT-045",
        assessment_type="college_aptitude",
        question='A class has 40 students and 30 passed. Pass percentage is:',
        options=['70%', '75%', '80%', '85%'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.PERCENTAGE,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='30/40×100 = 75%.',
    ),

    Question(
        question_code="COLLEGE-APT-046",
        assessment_type="college_aptitude",
        question='₹840 is divided in the ratio 3:4. The larger share is:',
        options=['₹360', '₹420', '₹480', '₹520'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.RATIO_PROPORTION,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='There are 7 parts; 840/7=120; larger share is 4×120 = ₹480.',
    ),

    Question(
        question_code="COLLEGE-APT-047",
        assessment_type="college_aptitude",
        question='The average of 8 numbers is 15. If one number 22 is removed, the new average is:',
        options=['13', '14', '14 1/7', '15'],
        answer="B",
        difficulty=Difficulty.MEDIUM,
        question_type=QuestionType.APTITUDE,
        topic=Topic.AVERAGE,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Total is 120; 120−22=98; 98/7 = 14.',
    ),

    Question(
        question_code="COLLEGE-APT-048",
        assessment_type="college_aptitude",
        question='A trader buys an item for ₹1,500 and gains 8%. Selling price is:',
        options=['₹1,580', '₹1,600', '₹1,620', '₹1,650'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.PROFIT_LOSS,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Gain is ₹120; selling price is ₹1,620.',
    ),

    Question(
        question_code="COLLEGE-APT-049",
        assessment_type="college_aptitude",
        question='The compound interest on ₹5,000 at 10% for 1 year is:',
        options=['₹400', '₹500', '₹550', '₹600'],
        answer="B",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.COMPOUND_INTEREST,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='For one year, compound interest is ₹500.',
    ),

    Question(
        question_code="COLLEGE-APT-050",
        assessment_type="college_aptitude",
        question='Two cities are 180 km apart. A car covers the distance in 3 hours. Speed is:',
        options=['50 km/h', '55 km/h', '60 km/h', '65 km/h'],
        answer="C",
        difficulty=Difficulty.EASY,
        question_type=QuestionType.APTITUDE,
        topic=Topic.TIME_DISTANCE,
        category="college_aptitude",
        user_role="college_student",
        skill="aptitude",
        explanation='Speed = 180/3 = 60 km/h.',
    ),

]