"""create email otp table

Revision ID: 8868ce6f9569
Revises: 91c700960bd3
Create Date: 2026-07-28 23:22:48.130146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8868ce6f9569'
down_revision: Union[str, Sequence[str], None] = '91c700960bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # The previous otp_verification revision already creates email_otps.
    # Keep this historical revision as a compatibility no-op.
    op.create_index(op.f("ix_email_otps_id"), "email_otps", ["id"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_otps_id'), table_name='email_otps')
    op.drop_table('email_otps')
    # ### end Alembic commands ###
