"""add role specific profile fields

Revision ID: a192d5b399e1
Revises: 5cacfbf97e45
Create Date: 2026-07-27 13:27:45.539211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a192d5b399e1'
down_revision: Union[str, Sequence[str], None] = '5cacfbf97e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('school_name', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('student_class', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('stream', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('professional_domain', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_profiles_branch'), 'profiles', ['branch'], unique=False)
    op.create_index(op.f('ix_profiles_experience_level'), 'profiles', ['experience_level'], unique=False)
    op.create_index(op.f('ix_profiles_professional_domain'), 'profiles', ['professional_domain'], unique=False)
    op.create_index(op.f('ix_profiles_stream'), 'profiles', ['stream'], unique=False)
    op.create_index(op.f('ix_profiles_student_class'), 'profiles', ['student_class'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_student_class'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_stream'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_professional_domain'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_experience_level'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_branch'), table_name='profiles')
    op.drop_column('profiles', 'years_of_experience')
    op.drop_column('profiles', 'experience_level')
    op.drop_column('profiles', 'professional_domain')
    op.drop_column('profiles', 'job_title')
    op.drop_column('profiles', 'company_name')
    op.drop_column('profiles', 'stream')
    op.drop_column('profiles', 'student_class')
    op.drop_column('profiles', 'school_name')
    # ### end Alembic commands ###
