"""add assessment question context

Revision ID: 5cacfbf97e45
Revises: e5e9d6ead6d5
Create Date: 2026-07-27 12:55:37.371426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cacfbf97e45'
down_revision: Union[str, Sequence[str], None] = 'e5e9d6ead6d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_questions', sa.Column('user_role', sa.String(), nullable=True))
    op.add_column('assessment_questions', sa.Column('category', sa.String(), nullable=True))
    op.add_column('assessment_questions', sa.Column('skill', sa.String(), nullable=True))
    op.add_column('assessment_questions', sa.Column('student_class', sa.String(), nullable=True))
    op.add_column('assessment_questions', sa.Column('stream', sa.String(), nullable=True))
    op.add_column('assessment_questions', sa.Column('degree', sa.String(), nullable=True))
    op.add_column('assessment_questions', sa.Column('branch', sa.String(), nullable=True))
    op.add_column('assessment_questions', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('assessment_questions', sa.Column('domain', sa.String(), nullable=True))
    op.create_index(op.f('ix_assessment_questions_branch'), 'assessment_questions', ['branch'], unique=False)
    op.create_index(op.f('ix_assessment_questions_category'), 'assessment_questions', ['category'], unique=False)
    op.create_index(op.f('ix_assessment_questions_degree'), 'assessment_questions', ['degree'], unique=False)
    op.create_index(op.f('ix_assessment_questions_domain'), 'assessment_questions', ['domain'], unique=False)
    op.create_index(op.f('ix_assessment_questions_experience_level'), 'assessment_questions', ['experience_level'], unique=False)
    op.create_index(op.f('ix_assessment_questions_skill'), 'assessment_questions', ['skill'], unique=False)
    op.create_index(op.f('ix_assessment_questions_stream'), 'assessment_questions', ['stream'], unique=False)
    op.create_index(op.f('ix_assessment_questions_student_class'), 'assessment_questions', ['student_class'], unique=False)
    op.create_index(op.f('ix_assessment_questions_user_role'), 'assessment_questions', ['user_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_questions_user_role'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_student_class'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_stream'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_skill'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_experience_level'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_domain'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_degree'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_category'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_branch'), table_name='assessment_questions')
    op.drop_column('assessment_questions', 'domain')
    op.drop_column('assessment_questions', 'experience_level')
    op.drop_column('assessment_questions', 'branch')
    op.drop_column('assessment_questions', 'degree')
    op.drop_column('assessment_questions', 'stream')
    op.drop_column('assessment_questions', 'student_class')
    op.drop_column('assessment_questions', 'skill')
    op.drop_column('assessment_questions', 'category')
    op.drop_column('assessment_questions', 'user_role')
    # ### end Alembic commands ###
