"""attempt questions

Revision ID: e5e9d6ead6d5
Revises: 0d00240bece6
Create Date: 2026-07-27 03:56:23.179742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e9d6ead6d5'
down_revision: Union[str, Sequence[str], None] = '0d00240bece6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_attempt_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_attempt_questions_attempt_id'), 'assessment_attempt_questions', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_assessment_attempt_questions_id'), 'assessment_attempt_questions', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_attempt_questions_question_id'), 'assessment_attempt_questions', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_attempt_questions_question_id'), table_name='assessment_attempt_questions')
    op.drop_index(op.f('ix_assessment_attempt_questions_id'), table_name='assessment_attempt_questions')
    op.drop_index(op.f('ix_assessment_attempt_questions_attempt_id'), table_name='assessment_attempt_questions')
    op.drop_table('assessment_attempt_questions')
    # ### end Alembic commands ###
