"""add linkedin url to profile

Revision ID: bdc38599108f
Revises: 26662a50c62a
Create Date: 2026-07-27 01:50:09.310196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc38599108f'
down_revision: Union[str, Sequence[str], None] = '26662a50c62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('linkedin_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'linkedin_url')
    # ### end Alembic commands ###
