import { useState } from "react";import { Bot, Send } from "lucide-react";import { useAuth } from "../../contexts/AuthContext";import { calculateWorkspaceStats } from "../../services/highSchoolWorkspaceService";import { generateFinalStreamGuidance } from "../../data/assessment/streamGuidanceService";import { getHighSchoolProfile } from "../../services/highSchoolProfileService";
type Message={role:"user"|"assistant";text:string};
function AILearningSupport(){const {user}=useAuth();const [question,setQuestion]=useState("");const [messages,setMessages]=useState<Message[]>([{role:"assistant",text:"Hello! I can explain your TalentSphere progress, assessments, goals, assignments, study planning and career guidance."}]);if(!user)return null;
 const answer=(q:string)=>{const x=q.toLowerCase();const w=calculateWorkspaceStats(user.id);const g=generateFinalStreamGuidance(user.id);const p=getHighSchoolProfile(user.id);
  if(x.includes("assignment"))return `You have ${w.assignments.length-w.completedAssignments} unfinished assignment(s) and ${w.completedAssignments} completed assignment(s). Open Assignments to update their status.`;
  if(x.includes("goal"))return `Today's goal progress is ${w.goalPercent}%. You completed ${w.completedGoals} of ${w.goals.length} goal(s).`;
  if(x.includes("stream")||x.includes("career"))return g.ready?`Your current assessment evidence shows ${g.recommendedStream} as the top stream match at ${g.recommendationScore}% with ${g.confidenceLevel.toLowerCase()} confidence. This is guidance, not the only factor in your final decision.`:"Complete all five assessments first. Then I can explain your combined stream guidance using your actual assessment evidence.";
  if(x.includes("weak")||x.includes("improve"))return g.ready&&g.improvementSkills.length?`Your current improvement areas include ${g.improvementSkills.slice(0,3).map(s=>`${s.skill} (${s.percentage}%)`).join(", ")}. Add focused daily goals for the weakest two areas.`:"Complete assessments and update subject progress so I can point to specific improvement areas.";
  if(x.includes("exam"))return w.exams.length?`You have ${w.exams.length} exam(s) saved. The next saved exam is ${[...w.exams].sort((a,b)=>a.date.localeCompare(b.date))[0].subject}. Review Upcoming Exams for the full schedule.`:"No exams are saved yet. Add your actual schedule in Upcoming Exams.";
  if(x.includes("profile"))return p?`Your profile is set for Class ${p.studentClass}, ${p.board}. Keep your school and location details updated for better context.`:"Your High School profile is incomplete. Complete My Profile first.";
  return "For a practical answer, ask me about your assignments, daily goals, exams, profile, weak areas, assessments, stream or career guidance.";
 };
 const send=(text=question)=>{const q=text.trim();if(!q)return;setMessages(m=>[...m,{role:"user",text:q},{role:"assistant",text:answer(q)}]);setQuestion("")};
 const quick=["What should I improve?","Explain my stream guidance","How are my daily goals?","Do I have assignments?"];
 return <div className="mx-auto max-w-5xl space-y-5"><div><h1 className="text-3xl font-bold">AI Learning Support</h1><p className="mt-1 text-slate-600">A simple career and learning assistant grounded in your TalentSphere data.</p></div><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center gap-3 border-b p-4"><div className="iconbox"><Bot size={22}/></div><div><h2 className="font-bold">TalentSphere AI</h2><p className="text-xs text-slate-500">Student learning assistant</p></div></div><div className="max-h-[430px] min-h-[300px] space-y-3 overflow-y-auto p-5">{messages.map((m,i)=><div key={i} className={`max-w-2xl rounded-2xl p-4 text-sm leading-6 ${m.role==="assistant"?"bg-cyan-50 text-slate-700":"ml-auto bg-cyan-600 text-white"}`}>{m.text}</div>)}</div><div className="border-t p-4"><div className="mb-3 flex flex-wrap gap-2">{quick.map(q=><button key={q} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs text-slate-700" onClick={()=>send(q)}>{q}</button>)}</div><div className="flex gap-2"><input className="field flex-1" value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")send()}} placeholder="Ask about your learning or career progress..."/><button className="primary" onClick={()=>send()}><Send size={18}/><span className="hidden sm:inline">Send</span></button></div></div></section></div>}
export default AILearningSupport;