import { useEffect, useState } from "react";
import { ArrowRight, BarChart3 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { getAssessmentHistory, getAssessmentResult, type AssessmentResult } from "../../data/assessment/assessmentService";

export default function AssessmentReports(){
 const nav=useNavigate(); const [results,setResults]=useState<AssessmentResult[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{(async()=>{try{const h=await getAssessmentHistory();const done=h.filter(x=>x.status==="completed");const rs=await Promise.all(done.map(x=>getAssessmentResult(x.id)));const latest=new Map<string,AssessmentResult>();for(const r of rs)if(!latest.has(r.assessment_type))latest.set(r.assessment_type,r);setResults([...latest.values()]);}catch(e){setError(e instanceof Error?e.message:"Unable to load reports.");}finally{setLoading(false);}})();},[]);
 if(loading)return <div className="p-8 text-slate-500">Loading assessment reports…</div>;
 return <div className="space-y-7"><div><p className="font-semibold text-cyan-600">Assessment Reports</p><h1 className="mt-2 text-3xl font-black text-slate-900">Your latest assessment results</h1><p className="mt-3 max-w-3xl text-slate-600">Each card below is synchronized with the latest completed result stored by the backend.</p></div>{error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}{!results.length?<div className="rounded-3xl border bg-white p-10 text-center shadow-sm"><BarChart3 size={48} className="mx-auto text-slate-300"/><h2 className="mt-5 text-xl font-bold">No report available</h2><p className="mt-2 text-slate-500">Complete an assessment to create your first report.</p><button onClick={()=>nav("/high_school_student/assessment")} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-cyan-600 px-6 py-3 font-semibold text-white">Go to Assessment <ArrowRight size={17}/></button></div>:<div className="grid gap-5 md:grid-cols-2">{results.map(r=><div key={r.attempt_id} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold uppercase tracking-wide text-cyan-600">{r.assessment_type.replaceAll("_"," ")}</p><h2 className="mt-2 text-3xl font-black text-slate-900">{Math.round(r.percentage)}%</h2></div><div className="rounded-2xl bg-cyan-50 p-3 text-cyan-700"><BarChart3 size={22}/></div></div><p className="mt-3 text-slate-600">{r.correct_answers}/{r.total_questions} correct • Grade {r.grade??"—"}</p>{r.strengths.length>0&&<div className="mt-5"><p className="text-sm font-bold text-emerald-700">Strengths</p><div className="mt-2 flex flex-wrap gap-2">{r.strengths.slice(0,4).map(x=><span key={x} className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700">{x}</span>)}</div></div>}{r.weaknesses.length>0&&<div className="mt-4"><p className="text-sm font-bold text-amber-700">Improve</p><div className="mt-2 flex flex-wrap gap-2">{r.weaknesses.slice(0,4).map(x=><span key={x} className="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-semibold text-amber-700">{x}</span>)}</div></div>}</div>)}</div>}</div>;
}
