import { useEffect, useState } from "react";
import { CheckCircle2, Clock3, Plus, Trash2 } from "lucide-react";
import { useAuth } from "../../contexts/AuthContext";
import { getGoals, saveGoals, todayKey, type DailyGoalItem } from "../../services/highSchoolWorkspaceService";
function DailyGoal(){const {user}=useAuth();const [goals,setGoals]=useState<DailyGoalItem[]>([]);const [title,setTitle]=useState("");const [minutes,setMinutes]=useState(30);
 useEffect(()=>{if(user)setGoals(getGoals(user.id))},[user]);const today=todayKey();const current=goals.filter(g=>g.date===today);const done=current.filter(g=>g.completed).length;const percent=current.length?Math.round(done/current.length*100):0;
 const persist=(n:DailyGoalItem[])=>{if(user){setGoals(n);saveGoals(user.id,n)}};const add=(e:React.FormEvent)=>{e.preventDefault();if(!title.trim())return;persist([...goals,{id:crypto.randomUUID(),title:title.trim(),minutes,completed:false,date:today}]);setTitle("");setMinutes(30)};
 return <div className="mx-auto max-w-5xl space-y-5"><div><h1 className="text-3xl font-bold text-slate-900">Daily Goals</h1><p className="mt-1 text-slate-600">Create and complete today's real learning targets.</p></div>
 <section className="rounded-2xl bg-gradient-to-r from-cyan-600 to-blue-600 p-6 text-white"><div className="flex justify-between"><h2 className="text-xl font-bold">Today's Progress</h2><strong>{percent}%</strong></div><div className="mt-4 h-3 rounded-full bg-white/20"><div className="h-3 rounded-full bg-white transition-all" style={{width:`${percent}%`}}/></div><p className="mt-2 text-cyan-100">{done} of {current.length} {current.length===1?"Goal":"Goals"} Completed</p></section>
 <form onSubmit={add} className="flex flex-col gap-3 rounded-2xl border bg-white p-4 sm:flex-row"><input className="field flex-1" placeholder="Today's learning goal" value={title} onChange={e=>setTitle(e.target.value)}/><input className="field sm:w-36" type="number" min="5" max="600" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/><button className="primary"><Plus size={17}/>Add Goal</button></form>
 {!current.length?<div className="rounded-2xl border border-dashed bg-white p-10 text-center text-slate-500">No goal for today. Add one to start tracking.</div>:<div className="space-y-3">{current.map(g=><div key={g.id} className="flex flex-col justify-between gap-3 rounded-2xl border bg-white p-5 sm:flex-row sm:items-center"><div><h2 className={`text-lg font-bold ${g.completed?"text-slate-400 line-through":"text-slate-900"}`}>{g.title}</h2><p className="mt-1 flex items-center gap-2 text-sm text-slate-500"><Clock3 size={15}/>{g.minutes} minutes</p></div><div className="flex gap-2"><button className={g.completed?"secondary":"primary"} onClick={()=>persist(goals.map(x=>x.id===g.id?{...x,completed:!x.completed}:x))}><CheckCircle2 size={17}/>{g.completed?"Mark Pending":"Complete"}</button><button className="iconbtn text-red-600" onClick={()=>persist(goals.filter(x=>x.id!==g.id))}><Trash2 size={17}/></button></div></div>)}</div>}</div>}
export default DailyGoal;