import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, Compass, TrendingUp } from "lucide-react";
import { loadFinalStreamGuidance, type StreamGuidanceResult } from "../../data/assessment/streamGuidanceService";

export default function FinalGuidanceReport(){
 const [guidance,setGuidance]=useState<StreamGuidanceResult|null>(null); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{void loadFinalStreamGuidance().then(setGuidance).catch(e=>setError(e instanceof Error?e.message:"Unable to load guidance."));},[]);
 if(error)return <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-700">{error}</div>;
 if(!guidance)return <div className="p-8 text-slate-500">Loading final guidance…</div>;
 if(!guidance.ready)return <div className="space-y-6"><div><p className="font-semibold text-cyan-600">Final Guidance Report</p><h1 className="mt-2 text-3xl font-black text-slate-900">Evidence-based career direction</h1><p className="mt-3 text-slate-600">You do not need to complete five assessments. Complete any relevant assessment and your latest saved result will be used as evidence.</p></div><div className="rounded-3xl border border-amber-200 bg-amber-50 p-7"><AlertTriangle className="text-amber-600" size={36}/><h2 className="mt-4 text-2xl font-bold text-slate-900">Not ready yet</h2><p className="mt-2 text-slate-700">{guidance.summary}</p><div className="mt-5 rounded-xl bg-white/70 p-4 text-sm text-slate-600">No completed assessment result is currently available.</div></div></div>;
 return <div className="space-y-7"><div><p className="font-semibold text-cyan-600">Final Guidance Report</p><h1 className="mt-2 text-3xl font-black text-slate-900">Your assessment-based direction</h1><p className="mt-3 text-slate-600">{guidance.summary} Results are synchronized from the backend assessment history.</p></div><div className="grid gap-5 md:grid-cols-3"><div className="rounded-3xl bg-white p-6 shadow-sm border"><p className="text-sm text-slate-500">Recommended direction</p><p className="mt-2 text-2xl font-black text-slate-900">{guidance.recommendedStream}</p></div><div className="rounded-3xl bg-white p-6 shadow-sm border"><p className="text-sm text-slate-500">Evidence score</p><p className="mt-2 text-3xl font-black text-cyan-700">{guidance.recommendationScore}%</p></div><div className="rounded-3xl bg-white p-6 shadow-sm border"><p className="text-sm text-slate-500">Confidence</p><p className="mt-2 text-2xl font-black text-slate-900">{guidance.confidenceLevel}</p></div></div><section className="rounded-3xl border bg-white p-7 shadow-sm"><div className="flex items-center gap-3"><Compass className="text-cyan-600"/><h2 className="text-xl font-bold">Assessment evidence</h2></div><div className="mt-5 grid gap-3 md:grid-cols-2">{guidance.results.map(r=><div key={r.attempt_id} className="flex items-center justify-between rounded-2xl bg-slate-50 p-4"><div><p className="font-bold text-slate-900">{r.assessment_type}</p><p className="text-sm text-slate-500">{r.correct_answers}/{r.total_questions} correct</p></div><span className="font-black text-cyan-700">{Math.round(r.percentage)}%</span></div>)}</div></section><section className="grid gap-5 md:grid-cols-2"><div className="rounded-3xl border bg-white p-7"><h2 className="text-xl font-bold">Strong areas</h2><div className="mt-4 space-y-2">{guidance.strongestSkills.length?guidance.strongestSkills.map(x=><div key={x.skill} className="flex justify-between rounded-xl bg-emerald-50 p-3"><span>{x.skill}</span><span className="font-bold text-emerald-700">{x.percentage}%</span></div>):<p className="text-slate-500">No skill-level evidence yet.</p>}</div></div><div className="rounded-3xl border bg-white p-7"><h2 className="text-xl font-bold">Next steps</h2><div className="mt-4 space-y-2">{guidance.nextSteps.map(x=><div key={x} className="flex gap-3 rounded-xl bg-slate-50 p-3"><TrendingUp size={18} className="mt-0.5 text-cyan-600"/><span>{x}</span></div>)}</div></div></section><div className="rounded-2xl bg-emerald-50 p-5 text-sm text-emerald-800"><CheckCircle2 className="mb-2" size={20}/>{guidance.recommendationReason}</div></div>;
}
