import { Bell, Search, X } from "lucide-react";import { useState } from "react";import { useNavigate } from "react-router-dom";import { useAuth } from "../../contexts/AuthContext";import { calculateWorkspaceStats } from "../../services/highSchoolWorkspaceService";
function HighSchoolTopbar(){const {user}=useAuth();const navigate=useNavigate();const [notice,setNotice]=useState(false);const [search,setSearch]=useState("");const name=user?.name?.trim()||"Student";const initial=name.charAt(0).toUpperCase()||"S";const stats=user?calculateWorkspaceStats(user.id):null;
 const pages=[["dashboard","/high-school-student/dashboard"],["profile","/high-school-student/profile"],["assessment","/high-school-student/assessment"],["assignments","/high-school-student/assignments"],["exams","/high-school-student/upcoming-exams"],["goals","/high-school-student/daily-goal"],["career","/high-school-student/career-explorer"],["settings","/high-school-student/settings"]];
 const submit=(e:React.FormEvent)=>{e.preventDefault();const hit=pages.find(([label])=>label.includes(search.toLowerCase().trim()));if(hit)navigate(hit[1])};
 return <header className="sticky top-16 z-30 border-b border-slate-200 bg-white lg:top-0"><div className="flex min-h-16 items-center justify-between gap-4 px-4 py-2.5 sm:px-5 lg:px-6"><div className="min-w-0 flex-1"><h1 className="truncate text-lg font-bold sm:text-xl">Welcome, {name} 👋</h1><p className="truncate text-xs text-slate-500">High School Student Dashboard</p></div><div className="relative flex items-center gap-2">
 <form onSubmit={submit} className="relative hidden xl:block"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search pages..." className="w-52 rounded-xl border py-2 pl-10 pr-3 text-sm"/></form>
 <button type="button" aria-label="Notifications" onClick={()=>setNotice(!notice)} className="relative iconbtn"><Bell size={19}/>{stats&&stats.assignments.length-stats.completedAssignments>0&&<span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-red-500"/>}</button>
 <button onClick={()=>navigate("/high-school-student/profile")} className="flex items-center gap-2 rounded-xl border p-1.5 sm:px-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-cyan-600 font-bold text-white">{initial}</div><div className="hidden text-left md:block"><h3 className="max-w-32 truncate text-sm font-semibold">{name}</h3><p className="text-xs text-slate-500">High School Student</p></div></button>
 {notice&&<div className="absolute right-0 top-14 w-80 rounded-2xl border bg-white p-4 shadow-xl"><div className="flex justify-between"><h2 className="font-bold">Notifications</h2><button onClick={()=>setNotice(false)}><X size={17}/></button></div><div className="mt-3 space-y-2 text-sm text-slate-600"><p className="rounded-lg bg-slate-50 p-3">{stats ? stats.assignments.length - stats.completedAssignments : 0} unfinished assignment(s).</p><p className="rounded-lg bg-slate-50 p-3">{stats?.exams.length||0} exam(s) saved.</p><p className="rounded-lg bg-slate-50 p-3">Today's goal progress: {stats?.goalPercent||0}%.</p></div></div>}
 </div></div></header>}
export default HighSchoolTopbar;